/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.edirectory.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EDDepartment service. Represents a row in the &quot;EDDepartment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.edirectory.model.impl.EDDepartmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.edirectory.model.impl.EDDepartmentImpl}.
 * </p>
 *
 * @author HOAN
 * @see EDDepartment
 * @see com.vportal.portlet.edirectory.model.impl.EDDepartmentImpl
 * @see com.vportal.portlet.edirectory.model.impl.EDDepartmentModelImpl
 * @generated
 */
public interface EDDepartmentModel extends BaseModel<EDDepartment> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e d department model instance should use the {@link EDDepartment} interface instead.
	 */

	/**
	 * Returns the primary key of this e d department.
	 *
	 * @return the primary key of this e d department
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e d department.
	 *
	 * @param primaryKey the primary key of this e d department
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this e d department.
	 *
	 * @return the ID of this e d department
	 */
	public long getId();

	/**
	 * Sets the ID of this e d department.
	 *
	 * @param id the ID of this e d department
	 */
	public void setId(long id);

	/**
	 * Returns the created date of this e d department.
	 *
	 * @return the created date of this e d department
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this e d department.
	 *
	 * @param createdDate the created date of this e d department
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the name of this e d department.
	 *
	 * @return the name of this e d department
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this e d department.
	 *
	 * @param name the name of this e d department
	 */
	public void setName(String name);

	/**
	 * Returns the parent of this e d department.
	 *
	 * @return the parent of this e d department
	 */
	public long getParent();

	/**
	 * Sets the parent of this e d department.
	 *
	 * @param parent the parent of this e d department
	 */
	public void setParent(long parent);

	/**
	 * Returns the phone of this e d department.
	 *
	 * @return the phone of this e d department
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this e d department.
	 *
	 * @param phone the phone of this e d department
	 */
	public void setPhone(String phone);

	/**
	 * Returns the fax of this e d department.
	 *
	 * @return the fax of this e d department
	 */
	@AutoEscape
	public String getFax();

	/**
	 * Sets the fax of this e d department.
	 *
	 * @param fax the fax of this e d department
	 */
	public void setFax(String fax);

	/**
	 * Returns the level ed of this e d department.
	 *
	 * @return the level ed of this e d department
	 */
	public long getLevelEd();

	/**
	 * Sets the level ed of this e d department.
	 *
	 * @param levelEd the level ed of this e d department
	 */
	public void setLevelEd(long levelEd);

	/**
	 * Returns the email of this e d department.
	 *
	 * @return the email of this e d department
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this e d department.
	 *
	 * @param email the email of this e d department
	 */
	public void setEmail(String email);

	/**
	 * Returns the address of this e d department.
	 *
	 * @return the address of this e d department
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this e d department.
	 *
	 * @param address the address of this e d department
	 */
	public void setAddress(String address);

	/**
	 * Returns the description of this e d department.
	 *
	 * @return the description of this e d department
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this e d department.
	 *
	 * @param description the description of this e d department
	 */
	public void setDescription(String description);

	/**
	 * Returns the website of this e d department.
	 *
	 * @return the website of this e d department
	 */
	@AutoEscape
	public String getWebsite();

	/**
	 * Sets the website of this e d department.
	 *
	 * @param website the website of this e d department
	 */
	public void setWebsite(String website);

	/**
	 * Returns the imgurl of this e d department.
	 *
	 * @return the imgurl of this e d department
	 */
	@AutoEscape
	public String getImgurl();

	/**
	 * Sets the imgurl of this e d department.
	 *
	 * @param imgurl the imgurl of this e d department
	 */
	public void setImgurl(String imgurl);

	/**
	 * Returns the company ID of this e d department.
	 *
	 * @return the company ID of this e d department
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this e d department.
	 *
	 * @param companyId the company ID of this e d department
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this e d department.
	 *
	 * @return the group ID of this e d department
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this e d department.
	 *
	 * @param groupId the group ID of this e d department
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this e d department.
	 *
	 * @return the user ID of this e d department
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this e d department.
	 *
	 * @param userId the user ID of this e d department
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this e d department.
	 *
	 * @return the user uuid of this e d department
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this e d department.
	 *
	 * @param userUuid the user uuid of this e d department
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the language ID of this e d department.
	 *
	 * @return the language ID of this e d department
	 */
	@AutoEscape
	public String getLanguageId();

	/**
	 * Sets the language ID of this e d department.
	 *
	 * @param languageId the language ID of this e d department
	 */
	public void setLanguageId(String languageId);

	/**
	 * Returns the domain ID of this e d department.
	 *
	 * @return the domain ID of this e d department
	 */
	@AutoEscape
	public String getDomainId();

	/**
	 * Sets the domain ID of this e d department.
	 *
	 * @param domainId the domain ID of this e d department
	 */
	public void setDomainId(String domainId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(EDDepartment edDepartment);

	public int hashCode();

	public CacheModel<EDDepartment> toCacheModel();

	public EDDepartment toEscapedModel();

	public String toString();

	public String toXmlString();
}