/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.edirectory.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EDEmployee service. Represents a row in the &quot;EDEmployee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.edirectory.model.impl.EDEmployeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.edirectory.model.impl.EDEmployeeImpl}.
 * </p>
 *
 * @author HOAN
 * @see EDEmployee
 * @see com.vportal.portlet.edirectory.model.impl.EDEmployeeImpl
 * @see com.vportal.portlet.edirectory.model.impl.EDEmployeeModelImpl
 * @generated
 */
public interface EDEmployeeModel extends BaseModel<EDEmployee> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e d employee model instance should use the {@link EDEmployee} interface instead.
	 */

	/**
	 * Returns the primary key of this e d employee.
	 *
	 * @return the primary key of this e d employee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e d employee.
	 *
	 * @param primaryKey the primary key of this e d employee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this e d employee.
	 *
	 * @return the uuid of this e d employee
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this e d employee.
	 *
	 * @param uuid the uuid of this e d employee
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this e d employee.
	 *
	 * @return the ID of this e d employee
	 */
	public long getId();

	/**
	 * Sets the ID of this e d employee.
	 *
	 * @param id the ID of this e d employee
	 */
	public void setId(long id);

	/**
	 * Returns the created date of this e d employee.
	 *
	 * @return the created date of this e d employee
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this e d employee.
	 *
	 * @param createdDate the created date of this e d employee
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this e d employee.
	 *
	 * @return the modified date of this e d employee
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this e d employee.
	 *
	 * @param modifiedDate the modified date of this e d employee
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this e d employee.
	 *
	 * @return the title of this e d employee
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this e d employee.
	 *
	 * @param title the title of this e d employee
	 */
	public void setTitle(String title);

	/**
	 * Returns the name of this e d employee.
	 *
	 * @return the name of this e d employee
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this e d employee.
	 *
	 * @param name the name of this e d employee
	 */
	public void setName(String name);

	/**
	 * Returns the birthday of this e d employee.
	 *
	 * @return the birthday of this e d employee
	 */
	public Date getBirthday();

	/**
	 * Sets the birthday of this e d employee.
	 *
	 * @param birthday the birthday of this e d employee
	 */
	public void setBirthday(Date birthday);

	/**
	 * Returns the home side of this e d employee.
	 *
	 * @return the home side of this e d employee
	 */
	@AutoEscape
	public String getHomeSide();

	/**
	 * Sets the home side of this e d employee.
	 *
	 * @param homeSide the home side of this e d employee
	 */
	public void setHomeSide(String homeSide);

	/**
	 * Returns the family of this e d employee.
	 *
	 * @return the family of this e d employee
	 */
	@AutoEscape
	public String getFamily();

	/**
	 * Sets the family of this e d employee.
	 *
	 * @param family the family of this e d employee
	 */
	public void setFamily(String family);

	/**
	 * Returns the race of this e d employee.
	 *
	 * @return the race of this e d employee
	 */
	@AutoEscape
	public String getRace();

	/**
	 * Sets the race of this e d employee.
	 *
	 * @param race the race of this e d employee
	 */
	public void setRace(String race);

	/**
	 * Returns the home of this e d employee.
	 *
	 * @return the home of this e d employee
	 */
	@AutoEscape
	public String getHome();

	/**
	 * Sets the home of this e d employee.
	 *
	 * @param home the home of this e d employee
	 */
	public void setHome(String home);

	/**
	 * Returns the home phone of this e d employee.
	 *
	 * @return the home phone of this e d employee
	 */
	@AutoEscape
	public String getHomePhone();

	/**
	 * Sets the home phone of this e d employee.
	 *
	 * @param homePhone the home phone of this e d employee
	 */
	public void setHomePhone(String homePhone);

	/**
	 * Returns the work phone of this e d employee.
	 *
	 * @return the work phone of this e d employee
	 */
	@AutoEscape
	public String getWorkPhone();

	/**
	 * Sets the work phone of this e d employee.
	 *
	 * @param workPhone the work phone of this e d employee
	 */
	public void setWorkPhone(String workPhone);

	/**
	 * Returns the mobile phone of this e d employee.
	 *
	 * @return the mobile phone of this e d employee
	 */
	@AutoEscape
	public String getMobilePhone();

	/**
	 * Sets the mobile phone of this e d employee.
	 *
	 * @param mobilePhone the mobile phone of this e d employee
	 */
	public void setMobilePhone(String mobilePhone);

	/**
	 * Returns the email of this e d employee.
	 *
	 * @return the email of this e d employee
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this e d employee.
	 *
	 * @param email the email of this e d employee
	 */
	public void setEmail(String email);

	/**
	 * Returns the department ID of this e d employee.
	 *
	 * @return the department ID of this e d employee
	 */
	public long getDepartmentId();

	/**
	 * Sets the department ID of this e d employee.
	 *
	 * @param departmentId the department ID of this e d employee
	 */
	public void setDepartmentId(long departmentId);

	/**
	 * Returns the major level of this e d employee.
	 *
	 * @return the major level of this e d employee
	 */
	@AutoEscape
	public String getMajorLevel();

	/**
	 * Sets the major level of this e d employee.
	 *
	 * @param majorLevel the major level of this e d employee
	 */
	public void setMajorLevel(String majorLevel);

	/**
	 * Returns the philosophism of this e d employee.
	 *
	 * @return the philosophism of this e d employee
	 */
	@AutoEscape
	public String getPhilosophism();

	/**
	 * Sets the philosophism of this e d employee.
	 *
	 * @param philosophism the philosophism of this e d employee
	 */
	public void setPhilosophism(String philosophism);

	/**
	 * Returns the foreign language of this e d employee.
	 *
	 * @return the foreign language of this e d employee
	 */
	@AutoEscape
	public String getForeignLanguage();

	/**
	 * Sets the foreign language of this e d employee.
	 *
	 * @param foreignLanguage the foreign language of this e d employee
	 */
	public void setForeignLanguage(String foreignLanguage);

	/**
	 * Returns the join date of this e d employee.
	 *
	 * @return the join date of this e d employee
	 */
	public Date getJoinDate();

	/**
	 * Sets the join date of this e d employee.
	 *
	 * @param joinDate the join date of this e d employee
	 */
	public void setJoinDate(Date joinDate);

	/**
	 * Returns the image of this e d employee.
	 *
	 * @return the image of this e d employee
	 */
	@AutoEscape
	public String getImage();

	/**
	 * Sets the image of this e d employee.
	 *
	 * @param image the image of this e d employee
	 */
	public void setImage(String image);

	/**
	 * Returns the is show tree of this e d employee.
	 *
	 * @return the is show tree of this e d employee
	 */
	public boolean getIsShowTree();

	/**
	 * Returns <code>true</code> if this e d employee is is show tree.
	 *
	 * @return <code>true</code> if this e d employee is is show tree; <code>false</code> otherwise
	 */
	public boolean isIsShowTree();

	/**
	 * Sets whether this e d employee is is show tree.
	 *
	 * @param isShowTree the is show tree of this e d employee
	 */
	public void setIsShowTree(boolean isShowTree);

	/**
	 * Returns the other info of this e d employee.
	 *
	 * @return the other info of this e d employee
	 */
	@AutoEscape
	public String getOtherInfo();

	/**
	 * Sets the other info of this e d employee.
	 *
	 * @param otherInfo the other info of this e d employee
	 */
	public void setOtherInfo(String otherInfo);

	/**
	 * Returns the company ID of this e d employee.
	 *
	 * @return the company ID of this e d employee
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this e d employee.
	 *
	 * @param companyId the company ID of this e d employee
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this e d employee.
	 *
	 * @return the group ID of this e d employee
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this e d employee.
	 *
	 * @param groupId the group ID of this e d employee
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this e d employee.
	 *
	 * @return the user ID of this e d employee
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this e d employee.
	 *
	 * @param userId the user ID of this e d employee
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this e d employee.
	 *
	 * @return the user uuid of this e d employee
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this e d employee.
	 *
	 * @param userUuid the user uuid of this e d employee
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the language ID of this e d employee.
	 *
	 * @return the language ID of this e d employee
	 */
	@AutoEscape
	public String getLanguageId();

	/**
	 * Sets the language ID of this e d employee.
	 *
	 * @param languageId the language ID of this e d employee
	 */
	public void setLanguageId(String languageId);

	/**
	 * Returns the display order of this e d employee.
	 *
	 * @return the display order of this e d employee
	 */
	public long getDisplayOrder();

	/**
	 * Sets the display order of this e d employee.
	 *
	 * @param displayOrder the display order of this e d employee
	 */
	public void setDisplayOrder(long displayOrder);

	/**
	 * Returns the sex of this e d employee.
	 *
	 * @return the sex of this e d employee
	 */
	@AutoEscape
	public String getSex();

	/**
	 * Sets the sex of this e d employee.
	 *
	 * @param sex the sex of this e d employee
	 */
	public void setSex(String sex);

	/**
	 * Returns the status of this e d employee.
	 *
	 * @return the status of this e d employee
	 */
	public long getStatus();

	/**
	 * Sets the status of this e d employee.
	 *
	 * @param status the status of this e d employee
	 */
	public void setStatus(long status);

	/**
	 * Returns the show of this e d employee.
	 *
	 * @return the show of this e d employee
	 */
	@AutoEscape
	public String getShow();

	/**
	 * Sets the show of this e d employee.
	 *
	 * @param show the show of this e d employee
	 */
	public void setShow(String show);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(EDEmployee edEmployee);

	public int hashCode();

	public CacheModel<EDEmployee> toCacheModel();

	public EDEmployee toEscapedModel();

	public String toString();

	public String toXmlString();
}