/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.edirectory.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EDFunction service. Represents a row in the &quot;EDFunction&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.edirectory.model.impl.EDFunctionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.edirectory.model.impl.EDFunctionImpl}.
 * </p>
 *
 * @author HOAN
 * @see EDFunction
 * @see com.vportal.portlet.edirectory.model.impl.EDFunctionImpl
 * @see com.vportal.portlet.edirectory.model.impl.EDFunctionModelImpl
 * @generated
 */
public interface EDFunctionModel extends BaseModel<EDFunction> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e d function model instance should use the {@link EDFunction} interface instead.
	 */

	/**
	 * Returns the primary key of this e d function.
	 *
	 * @return the primary key of this e d function
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e d function.
	 *
	 * @param primaryKey the primary key of this e d function
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this e d function.
	 *
	 * @return the ID of this e d function
	 */
	public long getId();

	/**
	 * Sets the ID of this e d function.
	 *
	 * @param id the ID of this e d function
	 */
	public void setId(long id);

	/**
	 * Returns the created date of this e d function.
	 *
	 * @return the created date of this e d function
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this e d function.
	 *
	 * @param createdDate the created date of this e d function
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the name of this e d function.
	 *
	 * @return the name of this e d function
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this e d function.
	 *
	 * @param name the name of this e d function
	 */
	public void setName(String name);

	/**
	 * Returns the level ed of this e d function.
	 *
	 * @return the level ed of this e d function
	 */
	public int getLevelEd();

	/**
	 * Sets the level ed of this e d function.
	 *
	 * @param levelEd the level ed of this e d function
	 */
	public void setLevelEd(int levelEd);

	/**
	 * Returns the is show tree of this e d function.
	 *
	 * @return the is show tree of this e d function
	 */
	public boolean getIsShowTree();

	/**
	 * Returns <code>true</code> if this e d function is is show tree.
	 *
	 * @return <code>true</code> if this e d function is is show tree; <code>false</code> otherwise
	 */
	public boolean isIsShowTree();

	/**
	 * Sets whether this e d function is is show tree.
	 *
	 * @param isShowTree the is show tree of this e d function
	 */
	public void setIsShowTree(boolean isShowTree);

	/**
	 * Returns the description of this e d function.
	 *
	 * @return the description of this e d function
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this e d function.
	 *
	 * @param description the description of this e d function
	 */
	public void setDescription(String description);

	/**
	 * Returns the group ID of this e d function.
	 *
	 * @return the group ID of this e d function
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this e d function.
	 *
	 * @param groupId the group ID of this e d function
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this e d function.
	 *
	 * @return the user ID of this e d function
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this e d function.
	 *
	 * @param userId the user ID of this e d function
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this e d function.
	 *
	 * @return the user uuid of this e d function
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this e d function.
	 *
	 * @param userUuid the user uuid of this e d function
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the company ID of this e d function.
	 *
	 * @return the company ID of this e d function
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this e d function.
	 *
	 * @param companyId the company ID of this e d function
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the language ID of this e d function.
	 *
	 * @return the language ID of this e d function
	 */
	@AutoEscape
	public String getLanguageId();

	/**
	 * Sets the language ID of this e d function.
	 *
	 * @param languageId the language ID of this e d function
	 */
	public void setLanguageId(String languageId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(EDFunction edFunction);

	public int hashCode();

	public CacheModel<EDFunction> toCacheModel();

	public EDFunction toEscapedModel();

	public String toString();

	public String toXmlString();
}