/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.edirectory.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EDFunctionDepartment service. Represents a row in the &quot;EDFunctionDepartment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.edirectory.model.impl.EDFunctionDepartmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.edirectory.model.impl.EDFunctionDepartmentImpl}.
 * </p>
 *
 * @author HOAN
 * @see EDFunctionDepartment
 * @see com.vportal.portlet.edirectory.model.impl.EDFunctionDepartmentImpl
 * @see com.vportal.portlet.edirectory.model.impl.EDFunctionDepartmentModelImpl
 * @generated
 */
public interface EDFunctionDepartmentModel extends BaseModel<EDFunctionDepartment> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e d function department model instance should use the {@link EDFunctionDepartment} interface instead.
	 */

	/**
	 * Returns the primary key of this e d function department.
	 *
	 * @return the primary key of this e d function department
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e d function department.
	 *
	 * @param primaryKey the primary key of this e d function department
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this e d function department.
	 *
	 * @return the ID of this e d function department
	 */
	public long getId();

	/**
	 * Sets the ID of this e d function department.
	 *
	 * @param id the ID of this e d function department
	 */
	public void setId(long id);

	/**
	 * Returns the function ID of this e d function department.
	 *
	 * @return the function ID of this e d function department
	 */
	public long getFunctionId();

	/**
	 * Sets the function ID of this e d function department.
	 *
	 * @param functionId the function ID of this e d function department
	 */
	public void setFunctionId(long functionId);

	/**
	 * Returns the department ID of this e d function department.
	 *
	 * @return the department ID of this e d function department
	 */
	public long getDepartmentId();

	/**
	 * Sets the department ID of this e d function department.
	 *
	 * @param departmentId the department ID of this e d function department
	 */
	public void setDepartmentId(long departmentId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(EDFunctionDepartment edFunctionDepartment);

	public int hashCode();

	public CacheModel<EDFunctionDepartment> toCacheModel();

	public EDFunctionDepartment toEscapedModel();

	public String toString();

	public String toXmlString();
}