/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.edirectory.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EDFunctionEmployee service. Represents a row in the &quot;EDFunctionEmployee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.edirectory.model.impl.EDFunctionEmployeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.edirectory.model.impl.EDFunctionEmployeeImpl}.
 * </p>
 *
 * @author HOAN
 * @see EDFunctionEmployee
 * @see com.vportal.portlet.edirectory.model.impl.EDFunctionEmployeeImpl
 * @see com.vportal.portlet.edirectory.model.impl.EDFunctionEmployeeModelImpl
 * @generated
 */
public interface EDFunctionEmployeeModel extends BaseModel<EDFunctionEmployee> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e d function employee model instance should use the {@link EDFunctionEmployee} interface instead.
	 */

	/**
	 * Returns the primary key of this e d function employee.
	 *
	 * @return the primary key of this e d function employee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e d function employee.
	 *
	 * @param primaryKey the primary key of this e d function employee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this e d function employee.
	 *
	 * @return the uuid of this e d function employee
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this e d function employee.
	 *
	 * @param uuid the uuid of this e d function employee
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this e d function employee.
	 *
	 * @return the ID of this e d function employee
	 */
	public long getId();

	/**
	 * Sets the ID of this e d function employee.
	 *
	 * @param id the ID of this e d function employee
	 */
	public void setId(long id);

	/**
	 * Returns the function ID of this e d function employee.
	 *
	 * @return the function ID of this e d function employee
	 */
	public long getFunctionId();

	/**
	 * Sets the function ID of this e d function employee.
	 *
	 * @param functionId the function ID of this e d function employee
	 */
	public void setFunctionId(long functionId);

	/**
	 * Returns the employee ID of this e d function employee.
	 *
	 * @return the employee ID of this e d function employee
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this e d function employee.
	 *
	 * @param employeeId the employee ID of this e d function employee
	 */
	public void setEmployeeId(long employeeId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(EDFunctionEmployee edFunctionEmployee);

	public int hashCode();

	public CacheModel<EDFunctionEmployee> toCacheModel();

	public EDFunctionEmployee toEscapedModel();

	public String toString();

	public String toXmlString();
}