/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vadvman.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AdvItem service. Represents a row in the &quot;AdvItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vadvman.model.impl.AdvItemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vadvman.model.impl.AdvItemImpl}.
 * </p>
 *
 * @author DucNN
 * @see AdvItem
 * @see com.vportal.portlet.vadvman.model.impl.AdvItemImpl
 * @see com.vportal.portlet.vadvman.model.impl.AdvItemModelImpl
 * @generated
 */
public interface AdvItemModel extends BaseModel<AdvItem> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a adv item model instance should use the {@link AdvItem} interface instead.
	 */

	/**
	 * Returns the primary key of this adv item.
	 *
	 * @return the primary key of this adv item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this adv item.
	 *
	 * @param primaryKey the primary key of this adv item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the item ID of this adv item.
	 *
	 * @return the item ID of this adv item
	 */
	public long getItemId();

	/**
	 * Sets the item ID of this adv item.
	 *
	 * @param itemId the item ID of this adv item
	 */
	public void setItemId(long itemId);

	/**
	 * Returns the create date of this adv item.
	 *
	 * @return the create date of this adv item
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this adv item.
	 *
	 * @param createDate the create date of this adv item
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this adv item.
	 *
	 * @return the modified date of this adv item
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this adv item.
	 *
	 * @param modifiedDate the modified date of this adv item
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the expried date of this adv item.
	 *
	 * @return the expried date of this adv item
	 */
	public Date getExpriedDate();

	/**
	 * Sets the expried date of this adv item.
	 *
	 * @param expriedDate the expried date of this adv item
	 */
	public void setExpriedDate(Date expriedDate);

	/**
	 * Returns the group ID of this adv item.
	 *
	 * @return the group ID of this adv item
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this adv item.
	 *
	 * @param groupId the group ID of this adv item
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this adv item.
	 *
	 * @return the company ID of this adv item
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this adv item.
	 *
	 * @param companyId the company ID of this adv item
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the name of this adv item.
	 *
	 * @return the name of this adv item
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this adv item.
	 *
	 * @param name the name of this adv item
	 */
	public void setName(String name);

	/**
	 * Returns the description of this adv item.
	 *
	 * @return the description of this adv item
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this adv item.
	 *
	 * @param description the description of this adv item
	 */
	public void setDescription(String description);

	/**
	 * Returns the url of this adv item.
	 *
	 * @return the url of this adv item
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this adv item.
	 *
	 * @param url the url of this adv item
	 */
	public void setUrl(String url);

	/**
	 * Returns the is target blank of this adv item.
	 *
	 * @return the is target blank of this adv item
	 */
	public boolean getIsTargetBlank();

	/**
	 * Returns <code>true</code> if this adv item is is target blank.
	 *
	 * @return <code>true</code> if this adv item is is target blank; <code>false</code> otherwise
	 */
	public boolean isIsTargetBlank();

	/**
	 * Sets whether this adv item is is target blank.
	 *
	 * @param isTargetBlank the is target blank of this adv item
	 */
	public void setIsTargetBlank(boolean isTargetBlank);

	/**
	 * Returns the txt mouse over of this adv item.
	 *
	 * @return the txt mouse over of this adv item
	 */
	@AutoEscape
	public String getTxtMouseOver();

	/**
	 * Sets the txt mouse over of this adv item.
	 *
	 * @param txtMouseOver the txt mouse over of this adv item
	 */
	public void setTxtMouseOver(String txtMouseOver);

	/**
	 * Returns the folder ID of this adv item.
	 *
	 * @return the folder ID of this adv item
	 */
	public long getFolderId();

	/**
	 * Sets the folder ID of this adv item.
	 *
	 * @param folderId the folder ID of this adv item
	 */
	public void setFolderId(long folderId);

	/**
	 * Returns the status of this adv item.
	 *
	 * @return the status of this adv item
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this adv item is status.
	 *
	 * @return <code>true</code> if this adv item is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this adv item is status.
	 *
	 * @param status the status of this adv item
	 */
	public void setStatus(boolean status);

	/**
	 * Returns the type ID of this adv item.
	 *
	 * @return the type ID of this adv item
	 */
	public long getTypeId();

	/**
	 * Sets the type ID of this adv item.
	 *
	 * @param typeId the type ID of this adv item
	 */
	public void setTypeId(long typeId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(AdvItem advItem);

	public int hashCode();

	public CacheModel<AdvItem> toCacheModel();

	public AdvItem toEscapedModel();

	public String toString();

	public String toXmlString();
}