/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vadvman.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AdvType service. Represents a row in the &quot;AdvType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vadvman.model.impl.AdvTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vadvman.model.impl.AdvTypeImpl}.
 * </p>
 *
 * @author DucNN
 * @see AdvType
 * @see com.vportal.portlet.vadvman.model.impl.AdvTypeImpl
 * @see com.vportal.portlet.vadvman.model.impl.AdvTypeModelImpl
 * @generated
 */
public interface AdvTypeModel extends BaseModel<AdvType> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a adv type model instance should use the {@link AdvType} interface instead.
	 */

	/**
	 * Returns the primary key of this adv type.
	 *
	 * @return the primary key of this adv type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this adv type.
	 *
	 * @param primaryKey the primary key of this adv type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the type ID of this adv type.
	 *
	 * @return the type ID of this adv type
	 */
	public long getTypeId();

	/**
	 * Sets the type ID of this adv type.
	 *
	 * @param typeId the type ID of this adv type
	 */
	public void setTypeId(long typeId);

	/**
	 * Returns the create date of this adv type.
	 *
	 * @return the create date of this adv type
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this adv type.
	 *
	 * @param createDate the create date of this adv type
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this adv type.
	 *
	 * @return the modified date of this adv type
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this adv type.
	 *
	 * @param modifiedDate the modified date of this adv type
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the group ID of this adv type.
	 *
	 * @return the group ID of this adv type
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this adv type.
	 *
	 * @param groupId the group ID of this adv type
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this adv type.
	 *
	 * @return the company ID of this adv type
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this adv type.
	 *
	 * @param companyId the company ID of this adv type
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the name of this adv type.
	 *
	 * @return the name of this adv type
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this adv type.
	 *
	 * @param name the name of this adv type
	 */
	public void setName(String name);

	/**
	 * Returns the description of this adv type.
	 *
	 * @return the description of this adv type
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this adv type.
	 *
	 * @param description the description of this adv type
	 */
	public void setDescription(String description);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(AdvType advType);

	public int hashCode();

	public CacheModel<AdvType> toCacheModel();

	public AdvType toEscapedModel();

	public String toString();

	public String toXmlString();
}