/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vcms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VcmsAttachedMessage service. Represents a row in the &quot;VcmsAttachedMessage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vcms.model.impl.VcmsAttachedMessageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vcms.model.impl.VcmsAttachedMessageImpl}.
 * </p>
 *
 * @author hai
 * @see VcmsAttachedMessage
 * @see com.vportal.portlet.vcms.model.impl.VcmsAttachedMessageImpl
 * @see com.vportal.portlet.vcms.model.impl.VcmsAttachedMessageModelImpl
 * @generated
 */
public interface VcmsAttachedMessageModel extends BaseModel<VcmsAttachedMessage> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vcms attached message model instance should use the {@link VcmsAttachedMessage} interface instead.
	 */

	/**
	 * Returns the primary key of this vcms attached message.
	 *
	 * @return the primary key of this vcms attached message
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this vcms attached message.
	 *
	 * @param primaryKey the primary key of this vcms attached message
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the message ID of this vcms attached message.
	 *
	 * @return the message ID of this vcms attached message
	 */
	@AutoEscape
	public String getMessageId();

	/**
	 * Sets the message ID of this vcms attached message.
	 *
	 * @param messageId the message ID of this vcms attached message
	 */
	public void setMessageId(String messageId);

	/**
	 * Returns the group ID of this vcms attached message.
	 *
	 * @return the group ID of this vcms attached message
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this vcms attached message.
	 *
	 * @param groupId the group ID of this vcms attached message
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this vcms attached message.
	 *
	 * @return the company ID of this vcms attached message
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this vcms attached message.
	 *
	 * @param companyId the company ID of this vcms attached message
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the created date of this vcms attached message.
	 *
	 * @return the created date of this vcms attached message
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this vcms attached message.
	 *
	 * @param createdDate the created date of this vcms attached message
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the created by user of this vcms attached message.
	 *
	 * @return the created by user of this vcms attached message
	 */
	@AutoEscape
	public String getCreatedByUser();

	/**
	 * Sets the created by user of this vcms attached message.
	 *
	 * @param createdByUser the created by user of this vcms attached message
	 */
	public void setCreatedByUser(String createdByUser);

	/**
	 * Returns the article ID of this vcms attached message.
	 *
	 * @return the article ID of this vcms attached message
	 */
	@AutoEscape
	public String getArticleId();

	/**
	 * Sets the article ID of this vcms attached message.
	 *
	 * @param articleId the article ID of this vcms attached message
	 */
	public void setArticleId(String articleId);

	/**
	 * Returns the content of this vcms attached message.
	 *
	 * @return the content of this vcms attached message
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this vcms attached message.
	 *
	 * @param content the content of this vcms attached message
	 */
	public void setContent(String content);

	/**
	 * Returns the read message of this vcms attached message.
	 *
	 * @return the read message of this vcms attached message
	 */
	public boolean getReadMessage();

	/**
	 * Returns <code>true</code> if this vcms attached message is read message.
	 *
	 * @return <code>true</code> if this vcms attached message is read message; <code>false</code> otherwise
	 */
	public boolean isReadMessage();

	/**
	 * Sets whether this vcms attached message is read message.
	 *
	 * @param readMessage the read message of this vcms attached message
	 */
	public void setReadMessage(boolean readMessage);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VcmsAttachedMessage vcmsAttachedMessage);

	public int hashCode();

	public CacheModel<VcmsAttachedMessage> toCacheModel();

	public VcmsAttachedMessage toEscapedModel();

	public String toString();

	public String toXmlString();
}