/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vcms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import com.vportal.portlet.vcms.service.persistence.VcmsArticleTypePK;

import java.io.Serializable;

/**
 * The base model interface for the VcmsArticleType service. Represents a row in the &quot;VcmsArticleType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vcms.model.impl.VcmsArticleTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vcms.model.impl.VcmsArticleTypeImpl}.
 * </p>
 *
 * @author hai
 * @see VcmsArticleType
 * @see com.vportal.portlet.vcms.model.impl.VcmsArticleTypeImpl
 * @see com.vportal.portlet.vcms.model.impl.VcmsArticleTypeModelImpl
 * @generated
 */
public interface VcmsArticleTypeModel extends BaseModel<VcmsArticleType> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vcms article type model instance should use the {@link VcmsArticleType} interface instead.
	 */

	/**
	 * Returns the primary key of this vcms article type.
	 *
	 * @return the primary key of this vcms article type
	 */
	public VcmsArticleTypePK getPrimaryKey();

	/**
	 * Sets the primary key of this vcms article type.
	 *
	 * @param primaryKey the primary key of this vcms article type
	 */
	public void setPrimaryKey(VcmsArticleTypePK primaryKey);

	/**
	 * Returns the type ID of this vcms article type.
	 *
	 * @return the type ID of this vcms article type
	 */
	public long getTypeId();

	/**
	 * Sets the type ID of this vcms article type.
	 *
	 * @param typeId the type ID of this vcms article type
	 */
	public void setTypeId(long typeId);

	/**
	 * Returns the article ID of this vcms article type.
	 *
	 * @return the article ID of this vcms article type
	 */
	@AutoEscape
	public String getArticleId();

	/**
	 * Sets the article ID of this vcms article type.
	 *
	 * @param articleId the article ID of this vcms article type
	 */
	public void setArticleId(String articleId);

	/**
	 * Returns the position of this vcms article type.
	 *
	 * @return the position of this vcms article type
	 */
	public long getPosition();

	/**
	 * Sets the position of this vcms article type.
	 *
	 * @param position the position of this vcms article type
	 */
	public void setPosition(long position);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VcmsArticleType vcmsArticleType);

	public int hashCode();

	public CacheModel<VcmsArticleType> toCacheModel();

	public VcmsArticleType toEscapedModel();

	public String toString();

	public String toXmlString();
}