/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vcms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VcmsThread service. Represents a row in the &quot;VcmsThread&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vcms.model.impl.VcmsThreadModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vcms.model.impl.VcmsThreadImpl}.
 * </p>
 *
 * @author hai
 * @see VcmsThread
 * @see com.vportal.portlet.vcms.model.impl.VcmsThreadImpl
 * @see com.vportal.portlet.vcms.model.impl.VcmsThreadModelImpl
 * @generated
 */
public interface VcmsThreadModel extends BaseModel<VcmsThread> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vcms thread model instance should use the {@link VcmsThread} interface instead.
	 */

	/**
	 * Returns the primary key of this vcms thread.
	 *
	 * @return the primary key of this vcms thread
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this vcms thread.
	 *
	 * @param primaryKey the primary key of this vcms thread
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the thread ID of this vcms thread.
	 *
	 * @return the thread ID of this vcms thread
	 */
	@AutoEscape
	public String getThreadId();

	/**
	 * Sets the thread ID of this vcms thread.
	 *
	 * @param threadId the thread ID of this vcms thread
	 */
	public void setThreadId(String threadId);

	/**
	 * Returns the group ID of this vcms thread.
	 *
	 * @return the group ID of this vcms thread
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this vcms thread.
	 *
	 * @param groupId the group ID of this vcms thread
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this vcms thread.
	 *
	 * @return the company ID of this vcms thread
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this vcms thread.
	 *
	 * @param companyId the company ID of this vcms thread
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the created date of this vcms thread.
	 *
	 * @return the created date of this vcms thread
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this vcms thread.
	 *
	 * @param createdDate the created date of this vcms thread
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the created by user of this vcms thread.
	 *
	 * @return the created by user of this vcms thread
	 */
	@AutoEscape
	public String getCreatedByUser();

	/**
	 * Sets the created by user of this vcms thread.
	 *
	 * @param createdByUser the created by user of this vcms thread
	 */
	public void setCreatedByUser(String createdByUser);

	/**
	 * Returns the modified date of this vcms thread.
	 *
	 * @return the modified date of this vcms thread
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this vcms thread.
	 *
	 * @param modifiedDate the modified date of this vcms thread
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by user of this vcms thread.
	 *
	 * @return the modified by user of this vcms thread
	 */
	@AutoEscape
	public String getModifiedByUser();

	/**
	 * Sets the modified by user of this vcms thread.
	 *
	 * @param modifiedByUser the modified by user of this vcms thread
	 */
	public void setModifiedByUser(String modifiedByUser);

	/**
	 * Returns the title of this vcms thread.
	 *
	 * @return the title of this vcms thread
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this vcms thread.
	 *
	 * @param title the title of this vcms thread
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this vcms thread.
	 *
	 * @return the description of this vcms thread
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this vcms thread.
	 *
	 * @param description the description of this vcms thread
	 */
	public void setDescription(String description);

	/**
	 * Returns the has image of this vcms thread.
	 *
	 * @return the has image of this vcms thread
	 */
	public boolean getHasImage();

	/**
	 * Returns <code>true</code> if this vcms thread is has image.
	 *
	 * @return <code>true</code> if this vcms thread is has image; <code>false</code> otherwise
	 */
	public boolean isHasImage();

	/**
	 * Sets whether this vcms thread is has image.
	 *
	 * @param hasImage the has image of this vcms thread
	 */
	public void setHasImage(boolean hasImage);

	/**
	 * Returns the image of this vcms thread.
	 *
	 * @return the image of this vcms thread
	 */
	@AutoEscape
	public String getImage();

	/**
	 * Sets the image of this vcms thread.
	 *
	 * @param image the image of this vcms thread
	 */
	public void setImage(String image);

	/**
	 * Returns the language of this vcms thread.
	 *
	 * @return the language of this vcms thread
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this vcms thread.
	 *
	 * @param language the language of this vcms thread
	 */
	public void setLanguage(String language);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VcmsThread vcmsThread);

	public int hashCode();

	public CacheModel<VcmsThread> toCacheModel();

	public VcmsThread toEscapedModel();

	public String toString();

	public String toXmlString();
}