/**
 * Copyright (c) Vietsoftware, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vsitemap.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.vportal.portlet.vsitemap.model.VsmBranch;
import com.vportal.portlet.vsitemap.service.VsmBranchLocalServiceUtil;

/**
 * The extended model base implementation for the VsmBranch service. Represents a row in the &quot;VsmBranch&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VsmBranchImpl}.
 * </p>
 *
 * @author LongLH
 * @see VsmBranchImpl
 * @see com.vportal.portlet.vsitemap.model.VsmBranch
 * @generated
 */
public abstract class VsmBranchBaseImpl extends VsmBranchModelImpl
	implements VsmBranch {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vsm branch model instance should use the {@link VsmBranch} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			VsmBranchLocalServiceUtil.addVsmBranch(this);
		}
		else {
			VsmBranchLocalServiceUtil.updateVsmBranch(this);
		}
	}
}