/**
 * Copyright (c) Vietsoftware, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vimagegallery.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TFImage service. Represents a row in the &quot;TFImage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vimagegallery.model.impl.TFImageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vimagegallery.model.impl.TFImageImpl}.
 * </p>
 *
 * @author DucNN
 * @see TFImage
 * @see com.vportal.portlet.vimagegallery.model.impl.TFImageImpl
 * @see com.vportal.portlet.vimagegallery.model.impl.TFImageModelImpl
 * @generated
 */
public interface TFImageModel extends BaseModel<TFImage> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a t f image model instance should use the {@link TFImage} interface instead.
	 */

	/**
	 * Returns the primary key of this t f image.
	 *
	 * @return the primary key of this t f image
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this t f image.
	 *
	 * @param primaryKey the primary key of this t f image
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this t f image.
	 *
	 * @return the ID of this t f image
	 */
	public long getId();

	/**
	 * Sets the ID of this t f image.
	 *
	 * @param id the ID of this t f image
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this t f image.
	 *
	 * @return the group ID of this t f image
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this t f image.
	 *
	 * @param groupId the group ID of this t f image
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this t f image.
	 *
	 * @return the company ID of this t f image
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this t f image.
	 *
	 * @param companyId the company ID of this t f image
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this t f image.
	 *
	 * @return the user ID of this t f image
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this t f image.
	 *
	 * @param userId the user ID of this t f image
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this t f image.
	 *
	 * @return the user uuid of this t f image
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this t f image.
	 *
	 * @param userUuid the user uuid of this t f image
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this t f image.
	 *
	 * @return the create date of this t f image
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this t f image.
	 *
	 * @param createDate the create date of this t f image
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this t f image.
	 *
	 * @return the modified date of this t f image
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this t f image.
	 *
	 * @param modifiedDate the modified date of this t f image
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the category ID of this t f image.
	 *
	 * @return the category ID of this t f image
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this t f image.
	 *
	 * @param categoryId the category ID of this t f image
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the name of this t f image.
	 *
	 * @return the name of this t f image
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this t f image.
	 *
	 * @param name the name of this t f image
	 */
	public void setName(String name);

	/**
	 * Returns the description of this t f image.
	 *
	 * @return the description of this t f image
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this t f image.
	 *
	 * @param description the description of this t f image
	 */
	public void setDescription(String description);

	/**
	 * Returns the image of this t f image.
	 *
	 * @return the image of this t f image
	 */
	@AutoEscape
	public String getImage();

	/**
	 * Sets the image of this t f image.
	 *
	 * @param image the image of this t f image
	 */
	public void setImage(String image);

	/**
	 * Returns the is show of this t f image.
	 *
	 * @return the is show of this t f image
	 */
	public boolean getIsShow();

	/**
	 * Returns <code>true</code> if this t f image is is show.
	 *
	 * @return <code>true</code> if this t f image is is show; <code>false</code> otherwise
	 */
	public boolean isIsShow();

	/**
	 * Sets whether this t f image is is show.
	 *
	 * @param isShow the is show of this t f image
	 */
	public void setIsShow(boolean isShow);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TFImage tfImage);

	public int hashCode();

	public CacheModel<TFImage> toCacheModel();

	public TFImage toEscapedModel();

	public String toString();

	public String toXmlString();
}