/**
 * Copyright (c) Vietsoftware, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.edirectory.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.vportal.portlet.edirectory.model.EDDepartment;
import com.vportal.portlet.edirectory.service.EDDepartmentLocalServiceUtil;

/**
 * The extended model base implementation for the EDDepartment service. Represents a row in the &quot;EDDepartment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EDDepartmentImpl}.
 * </p>
 *
 * @author HOAN
 * @see EDDepartmentImpl
 * @see com.vportal.portlet.edirectory.model.EDDepartment
 * @generated
 */

public abstract class EDDepartmentBaseImpl extends EDDepartmentModelImpl
		implements EDDepartment {
	/*
	 * NOTE FOR DEVELOPERS:
	 * 
	 * Never modify or reference this class directly. All methods that expect a
	 * e d department model instance should use the {@link EDDepartment}
	 * interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			EDDepartmentLocalServiceUtil.addEDDepartment(this);
		} else {
			EDDepartmentLocalServiceUtil.updateEDDepartment(this);
		}
	}
}