/**
 * Copyright (c) Vietsoftware, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vdoc.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.base.PrincipalBean;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.vportal.portlet.vdoc.model.vdocField;
import com.vportal.portlet.vdoc.service.persistence.vdocDORelPersistence;
import com.vportal.portlet.vdoc.service.persistence.vdocDocumentFinder;
import com.vportal.portlet.vdoc.service.persistence.vdocDocumentPersistence;
import com.vportal.portlet.vdoc.service.persistence.vdocFieldPersistence;
import com.vportal.portlet.vdoc.service.persistence.vdocLoggerPersistence;
import com.vportal.portlet.vdoc.service.persistence.vdocOrgPersistence;
import com.vportal.portlet.vdoc.service.vdocDORelService;
import com.vportal.portlet.vdoc.service.vdocDocumentService;
import com.vportal.portlet.vdoc.service.vdocFieldService;
import com.vportal.portlet.vdoc.service.vdocLoggerService;
import com.vportal.portlet.vdoc.service.vdocOrgService;

import javax.sql.DataSource;

/**
 * The base implementation of the vdoc field remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.vportal.portlet.vdoc.service.impl.vdocFieldServiceImpl}.
 * </p>
 *
 * @author MrEn
 * @see com.vportal.portlet.vdoc.service.impl.vdocFieldServiceImpl
 * @see com.vportal.portlet.vdoc.service.vdocFieldServiceUtil
 * @generated
 */
public abstract class vdocFieldServiceBaseImpl extends PrincipalBean
	implements vdocFieldService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.vportal.portlet.vdoc.service.vdocFieldServiceUtil} to access the vdoc field remote service.
	 */

	/**
	 * Returns the vdoc document remote service.
	 *
	 * @return the vdoc document remote service
	 */
	public vdocDocumentService getvdocDocumentService() {
		return vdocDocumentService;
	}

	/**
	 * Sets the vdoc document remote service.
	 *
	 * @param vdocDocumentService the vdoc document remote service
	 */
	public void setvdocDocumentService(vdocDocumentService vdocDocumentService) {
		this.vdocDocumentService = vdocDocumentService;
	}

	/**
	 * Returns the vdoc document persistence.
	 *
	 * @return the vdoc document persistence
	 */
	public vdocDocumentPersistence getvdocDocumentPersistence() {
		return vdocDocumentPersistence;
	}

	/**
	 * Sets the vdoc document persistence.
	 *
	 * @param vdocDocumentPersistence the vdoc document persistence
	 */
	public void setvdocDocumentPersistence(
		vdocDocumentPersistence vdocDocumentPersistence) {
		this.vdocDocumentPersistence = vdocDocumentPersistence;
	}

	/**
	 * Returns the vdoc document finder.
	 *
	 * @return the vdoc document finder
	 */
	public vdocDocumentFinder getvdocDocumentFinder() {
		return vdocDocumentFinder;
	}

	/**
	 * Sets the vdoc document finder.
	 *
	 * @param vdocDocumentFinder the vdoc document finder
	 */
	public void setvdocDocumentFinder(vdocDocumentFinder vdocDocumentFinder) {
		this.vdocDocumentFinder = vdocDocumentFinder;
	}

	/**
	 * Returns the vdoc d o rel remote service.
	 *
	 * @return the vdoc d o rel remote service
	 */
	public vdocDORelService getvdocDORelService() {
		return vdocDORelService;
	}

	/**
	 * Sets the vdoc d o rel remote service.
	 *
	 * @param vdocDORelService the vdoc d o rel remote service
	 */
	public void setvdocDORelService(vdocDORelService vdocDORelService) {
		this.vdocDORelService = vdocDORelService;
	}

	/**
	 * Returns the vdoc d o rel persistence.
	 *
	 * @return the vdoc d o rel persistence
	 */
	public vdocDORelPersistence getvdocDORelPersistence() {
		return vdocDORelPersistence;
	}

	/**
	 * Sets the vdoc d o rel persistence.
	 *
	 * @param vdocDORelPersistence the vdoc d o rel persistence
	 */
	public void setvdocDORelPersistence(
		vdocDORelPersistence vdocDORelPersistence) {
		this.vdocDORelPersistence = vdocDORelPersistence;
	}

	/**
	 * Returns the vdoc field remote service.
	 *
	 * @return the vdoc field remote service
	 */
	public vdocFieldService getvdocFieldService() {
		return vdocFieldService;
	}

	/**
	 * Sets the vdoc field remote service.
	 *
	 * @param vdocFieldService the vdoc field remote service
	 */
	public void setvdocFieldService(vdocFieldService vdocFieldService) {
		this.vdocFieldService = vdocFieldService;
	}

	/**
	 * Returns the vdoc field persistence.
	 *
	 * @return the vdoc field persistence
	 */
	public vdocFieldPersistence getvdocFieldPersistence() {
		return vdocFieldPersistence;
	}

	/**
	 * Sets the vdoc field persistence.
	 *
	 * @param vdocFieldPersistence the vdoc field persistence
	 */
	public void setvdocFieldPersistence(
		vdocFieldPersistence vdocFieldPersistence) {
		this.vdocFieldPersistence = vdocFieldPersistence;
	}

	/**
	 * Returns the vdoc logger remote service.
	 *
	 * @return the vdoc logger remote service
	 */
	public vdocLoggerService getvdocLoggerService() {
		return vdocLoggerService;
	}

	/**
	 * Sets the vdoc logger remote service.
	 *
	 * @param vdocLoggerService the vdoc logger remote service
	 */
	public void setvdocLoggerService(vdocLoggerService vdocLoggerService) {
		this.vdocLoggerService = vdocLoggerService;
	}

	/**
	 * Returns the vdoc logger persistence.
	 *
	 * @return the vdoc logger persistence
	 */
	public vdocLoggerPersistence getvdocLoggerPersistence() {
		return vdocLoggerPersistence;
	}

	/**
	 * Sets the vdoc logger persistence.
	 *
	 * @param vdocLoggerPersistence the vdoc logger persistence
	 */
	public void setvdocLoggerPersistence(
		vdocLoggerPersistence vdocLoggerPersistence) {
		this.vdocLoggerPersistence = vdocLoggerPersistence;
	}

	/**
	 * Returns the vdoc org remote service.
	 *
	 * @return the vdoc org remote service
	 */
	public vdocOrgService getvdocOrgService() {
		return vdocOrgService;
	}

	/**
	 * Sets the vdoc org remote service.
	 *
	 * @param vdocOrgService the vdoc org remote service
	 */
	public void setvdocOrgService(vdocOrgService vdocOrgService) {
		this.vdocOrgService = vdocOrgService;
	}

	/**
	 * Returns the vdoc org persistence.
	 *
	 * @return the vdoc org persistence
	 */
	public vdocOrgPersistence getvdocOrgPersistence() {
		return vdocOrgPersistence;
	}

	/**
	 * Sets the vdoc org persistence.
	 *
	 * @param vdocOrgPersistence the vdoc org persistence
	 */
	public void setvdocOrgPersistence(vdocOrgPersistence vdocOrgPersistence) {
		this.vdocOrgPersistence = vdocOrgPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	protected Class<?> getModelClass() {
		return vdocField.class;
	}

	protected String getModelClassName() {
		return vdocField.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = vdocFieldPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = vdocDocumentService.class)
	protected vdocDocumentService vdocDocumentService;
	@BeanReference(type = vdocDocumentPersistence.class)
	protected vdocDocumentPersistence vdocDocumentPersistence;
	@BeanReference(type = vdocDocumentFinder.class)
	protected vdocDocumentFinder vdocDocumentFinder;
	@BeanReference(type = vdocDORelService.class)
	protected vdocDORelService vdocDORelService;
	@BeanReference(type = vdocDORelPersistence.class)
	protected vdocDORelPersistence vdocDORelPersistence;
	@BeanReference(type = vdocFieldService.class)
	protected vdocFieldService vdocFieldService;
	@BeanReference(type = vdocFieldPersistence.class)
	protected vdocFieldPersistence vdocFieldPersistence;
	@BeanReference(type = vdocLoggerService.class)
	protected vdocLoggerService vdocLoggerService;
	@BeanReference(type = vdocLoggerPersistence.class)
	protected vdocLoggerPersistence vdocLoggerPersistence;
	@BeanReference(type = vdocOrgService.class)
	protected vdocOrgService vdocOrgService;
	@BeanReference(type = vdocOrgPersistence.class)
	protected vdocOrgPersistence vdocOrgPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
}