/**
 * Copyright (c) Vietsoftware, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vdoc.model.impl;

import com.vportal.portlet.vdoc.model.vdocField;

/**
 * The extended model base implementation for the vdocField service. Represents a row in the &quot;vdocField&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vdocFieldImpl}.
 * </p>
 *
 * @author MrEn
 * @see vdocFieldImpl
 * @see com.vportal.portlet.vdoc.model.vdocField
 * @generated
 */
public abstract class vdocFieldBaseImpl extends vdocFieldModelImpl
	implements vdocField {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vdoc field model instance should use the {@link vdocField} interface instead.
	 */
}