/**
 * Copyright (c) Vietsoftware, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vclip.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.util.PortalUtil;

import com.vportal.portlet.vclip.model.Clip;
import com.vportal.portlet.vclip.model.ClipModel;
import com.vportal.portlet.vclip.model.ClipSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * The base model implementation for the Clip service. Represents a row in the &quot;Clip&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.vportal.portlet.vclip.model.ClipModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ClipImpl}.
 * </p>
 *
 * @author HOAN
 * @see ClipImpl
 * @see com.vportal.portlet.vclip.model.Clip
 * @see com.vportal.portlet.vclip.model.ClipModel
 * @generated
 */
@JSON(strict = true)
public class ClipModelImpl extends BaseModelImpl<Clip> implements ClipModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a clip model instance should use the {@link com.vportal.portlet.vclip.model.Clip} interface instead.
	 */
	public static final String TABLE_NAME = "Clip";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.VARCHAR },
			{ "clipTypeId", Types.VARCHAR },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createdDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "url", Types.VARCHAR },
			{ "name", Types.VARCHAR },
			{ "title", Types.VARCHAR },
			{ "image", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "active_", Types.BOOLEAN },
			{ "language", Types.VARCHAR },
			{ "hitcount", Types.BIGINT },
			{ "hitcountview", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table Clip (id_ VARCHAR(75) not null primary key,clipTypeId VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,createdDate DATE null,modifiedDate DATE null,url VARCHAR(550) null,name VARCHAR(2000) null,title VARCHAR(2000) null,image VARCHAR(75) null,description VARCHAR(2000) null,active_ BOOLEAN,language VARCHAR(75) null,hitcount LONG,hitcountview LONG)";
	public static final String TABLE_SQL_DROP = "drop table Clip";
	public static final String ORDER_BY_JPQL = " ORDER BY clip.createdDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY Clip.createdDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.vportal.portlet.vclip.model.Clip"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.vportal.portlet.vclip.model.Clip"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.vportal.portlet.vclip.model.Clip"),
			true);
	public static long ACTIVE_COLUMN_BITMASK = 1L;
	public static long CLIPTYPEID_COLUMN_BITMASK = 2L;
	public static long LANGUAGE_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Clip toModel(ClipSoap soapModel) {
		Clip model = new ClipImpl();

		model.setId(soapModel.getId());
		model.setClipTypeId(soapModel.getClipTypeId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setCreatedDate(soapModel.getCreatedDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setUrl(soapModel.getUrl());
		model.setName(soapModel.getName());
		model.setTitle(soapModel.getTitle());
		model.setImage(soapModel.getImage());
		model.setDescription(soapModel.getDescription());
		model.setActive(soapModel.getActive());
		model.setLanguage(soapModel.getLanguage());
		model.setHitcount(soapModel.getHitcount());
		model.setHitcountview(soapModel.getHitcountview());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Clip> toModels(ClipSoap[] soapModels) {
		List<Clip> models = new ArrayList<Clip>(soapModels.length);

		for (ClipSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.vportal.portlet.vclip.model.Clip"));

	public ClipModelImpl() {
	}

	public String getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(String primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	public Class<?> getModelClass() {
		return Clip.class;
	}

	public String getModelClassName() {
		return Clip.class.getName();
	}

	@JSON
	public String getId() {
		if (_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _id;
		}
	}

	public void setId(String id) {
		_id = id;
	}

	@JSON
	public String getClipTypeId() {
		if (_clipTypeId == null) {
			return StringPool.BLANK;
		}
		else {
			return _clipTypeId;
		}
	}

	public void setClipTypeId(String clipTypeId) {
		_columnBitmask |= CLIPTYPEID_COLUMN_BITMASK;

		if (_originalClipTypeId == null) {
			_originalClipTypeId = _clipTypeId;
		}

		_clipTypeId = clipTypeId;
	}

	public String getOriginalClipTypeId() {
		return GetterUtil.getString(_originalClipTypeId);
	}

	@JSON
	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	public Date getCreatedDate() {
		return _createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		_columnBitmask = -1L;

		_createdDate = createdDate;
	}

	@JSON
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	public String getUrl() {
		if (_url == null) {
			return StringPool.BLANK;
		}
		else {
			return _url;
		}
	}

	public void setUrl(String url) {
		_url = url;
	}

	@JSON
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public void setName(String name) {
		_name = name;
	}

	@JSON
	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	public void setTitle(String title) {
		_title = title;
	}

	@JSON
	public String getImage() {
		if (_image == null) {
			return StringPool.BLANK;
		}
		else {
			return _image;
		}
	}

	public void setImage(String image) {
		_image = image;
	}

	@JSON
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	public boolean getActive() {
		return _active;
	}

	public boolean isActive() {
		return _active;
	}

	public void setActive(boolean active) {
		_columnBitmask |= ACTIVE_COLUMN_BITMASK;

		if (!_setOriginalActive) {
			_setOriginalActive = true;

			_originalActive = _active;
		}

		_active = active;
	}

	public boolean getOriginalActive() {
		return _originalActive;
	}

	@JSON
	public String getLanguage() {
		if (_language == null) {
			return StringPool.BLANK;
		}
		else {
			return _language;
		}
	}

	public void setLanguage(String language) {
		_columnBitmask |= LANGUAGE_COLUMN_BITMASK;

		if (_originalLanguage == null) {
			_originalLanguage = _language;
		}

		_language = language;
	}

	public String getOriginalLanguage() {
		return GetterUtil.getString(_originalLanguage);
	}

	@JSON
	public long getHitcount() {
		return _hitcount;
	}

	public void setHitcount(long hitcount) {
		_hitcount = hitcount;
	}

	@JSON
	public long getHitcountview() {
		return _hitcountview;
	}

	public void setHitcountview(long hitcountview) {
		_hitcountview = hitcountview;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public Clip toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Clip)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		ClipImpl clipImpl = new ClipImpl();

		clipImpl.setId(getId());
		clipImpl.setClipTypeId(getClipTypeId());
		clipImpl.setGroupId(getGroupId());
		clipImpl.setCompanyId(getCompanyId());
		clipImpl.setUserId(getUserId());
		clipImpl.setCreatedDate(getCreatedDate());
		clipImpl.setModifiedDate(getModifiedDate());
		clipImpl.setUrl(getUrl());
		clipImpl.setName(getName());
		clipImpl.setTitle(getTitle());
		clipImpl.setImage(getImage());
		clipImpl.setDescription(getDescription());
		clipImpl.setActive(getActive());
		clipImpl.setLanguage(getLanguage());
		clipImpl.setHitcount(getHitcount());
		clipImpl.setHitcountview(getHitcountview());

		clipImpl.resetOriginalValues();

		return clipImpl;
	}

	public int compareTo(Clip clip) {
		int value = 0;

		value = DateUtil.compareTo(getCreatedDate(), clip.getCreatedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Clip clip = null;

		try {
			clip = (Clip)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String primaryKey = clip.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		ClipModelImpl clipModelImpl = this;

		clipModelImpl._originalClipTypeId = clipModelImpl._clipTypeId;

		clipModelImpl._originalActive = clipModelImpl._active;

		clipModelImpl._setOriginalActive = false;

		clipModelImpl._originalLanguage = clipModelImpl._language;

		clipModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Clip> toCacheModel() {
		ClipCacheModel clipCacheModel = new ClipCacheModel();

		clipCacheModel.id = getId();

		String id = clipCacheModel.id;

		if ((id != null) && (id.length() == 0)) {
			clipCacheModel.id = null;
		}

		clipCacheModel.clipTypeId = getClipTypeId();

		String clipTypeId = clipCacheModel.clipTypeId;

		if ((clipTypeId != null) && (clipTypeId.length() == 0)) {
			clipCacheModel.clipTypeId = null;
		}

		clipCacheModel.groupId = getGroupId();

		clipCacheModel.companyId = getCompanyId();

		clipCacheModel.userId = getUserId();

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			clipCacheModel.createdDate = createdDate.getTime();
		}
		else {
			clipCacheModel.createdDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			clipCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			clipCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		clipCacheModel.url = getUrl();

		String url = clipCacheModel.url;

		if ((url != null) && (url.length() == 0)) {
			clipCacheModel.url = null;
		}

		clipCacheModel.name = getName();

		String name = clipCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			clipCacheModel.name = null;
		}

		clipCacheModel.title = getTitle();

		String title = clipCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			clipCacheModel.title = null;
		}

		clipCacheModel.image = getImage();

		String image = clipCacheModel.image;

		if ((image != null) && (image.length() == 0)) {
			clipCacheModel.image = null;
		}

		clipCacheModel.description = getDescription();

		String description = clipCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			clipCacheModel.description = null;
		}

		clipCacheModel.active = getActive();

		clipCacheModel.language = getLanguage();

		String language = clipCacheModel.language;

		if ((language != null) && (language.length() == 0)) {
			clipCacheModel.language = null;
		}

		clipCacheModel.hitcount = getHitcount();

		clipCacheModel.hitcountview = getHitcountview();

		return clipCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(33);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", clipTypeId=");
		sb.append(getClipTypeId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", url=");
		sb.append(getUrl());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", image=");
		sb.append(getImage());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", active=");
		sb.append(getActive());
		sb.append(", language=");
		sb.append(getLanguage());
		sb.append(", hitcount=");
		sb.append(getHitcount());
		sb.append(", hitcountview=");
		sb.append(getHitcountview());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(52);

		sb.append("<model><model-name>");
		sb.append("com.vportal.portlet.vclip.model.Clip");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>clipTypeId</column-name><column-value><![CDATA[");
		sb.append(getClipTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>url</column-name><column-value><![CDATA[");
		sb.append(getUrl());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>image</column-name><column-value><![CDATA[");
		sb.append(getImage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>active</column-name><column-value><![CDATA[");
		sb.append(getActive());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>language</column-name><column-value><![CDATA[");
		sb.append(getLanguage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hitcount</column-name><column-value><![CDATA[");
		sb.append(getHitcount());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hitcountview</column-name><column-value><![CDATA[");
		sb.append(getHitcountview());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Clip.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Clip.class
		};
	private String _id;
	private String _clipTypeId;
	private String _originalClipTypeId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private Date _createdDate;
	private Date _modifiedDate;
	private String _url;
	private String _name;
	private String _title;
	private String _image;
	private String _description;
	private boolean _active;
	private boolean _originalActive;
	private boolean _setOriginalActive;
	private String _language;
	private String _originalLanguage;
	private long _hitcount;
	private long _hitcountview;
	private long _columnBitmask;
	private Clip _escapedModelProxy;
}