/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vcalendar.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VCal service. Represents a row in the &quot;VCal&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vcalendar.model.impl.VCalModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vcalendar.model.impl.VCalImpl}.
 * </p>
 *
 * @author LongLH
 * @see VCal
 * @see com.vportal.portlet.vcalendar.model.impl.VCalImpl
 * @see com.vportal.portlet.vcalendar.model.impl.VCalModelImpl
 * @generated
 */
public interface VCalModel extends BaseModel<VCal>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a v cal model instance should use the {@link VCal} interface instead.
	 */

	/**
	 * Returns the primary key of this v cal.
	 *
	 * @return the primary key of this v cal
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this v cal.
	 *
	 * @param primaryKey the primary key of this v cal
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cal ID of this v cal.
	 *
	 * @return the cal ID of this v cal
	 */
	public long getCalId();

	/**
	 * Sets the cal ID of this v cal.
	 *
	 * @param calId the cal ID of this v cal
	 */
	public void setCalId(long calId);

	/**
	 * Returns the group ID of this v cal.
	 *
	 * @return the group ID of this v cal
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this v cal.
	 *
	 * @param groupId the group ID of this v cal
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this v cal.
	 *
	 * @return the company ID of this v cal
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this v cal.
	 *
	 * @param companyId the company ID of this v cal
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this v cal.
	 *
	 * @return the user ID of this v cal
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this v cal.
	 *
	 * @param userId the user ID of this v cal
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this v cal.
	 *
	 * @return the user uuid of this v cal
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this v cal.
	 *
	 * @param userUuid the user uuid of this v cal
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this v cal.
	 *
	 * @return the user name of this v cal
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this v cal.
	 *
	 * @param userName the user name of this v cal
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this v cal.
	 *
	 * @return the create date of this v cal
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this v cal.
	 *
	 * @param createDate the create date of this v cal
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this v cal.
	 *
	 * @return the modified date of this v cal
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this v cal.
	 *
	 * @param modifiedDate the modified date of this v cal
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the language ID of this v cal.
	 *
	 * @return the language ID of this v cal
	 */
	@AutoEscape
	public String getLanguageId();

	/**
	 * Sets the language ID of this v cal.
	 *
	 * @param languageId the language ID of this v cal
	 */
	public void setLanguageId(String languageId);

	/**
	 * Returns the file ID of this v cal.
	 *
	 * @return the file ID of this v cal
	 */
	public long getFileId();

	/**
	 * Sets the file ID of this v cal.
	 *
	 * @param fileId the file ID of this v cal
	 */
	public void setFileId(long fileId);

	/**
	 * Returns the title of this v cal.
	 *
	 * @return the title of this v cal
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this v cal.
	 *
	 * @param title the title of this v cal
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this v cal.
	 *
	 * @return the description of this v cal
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this v cal.
	 *
	 * @param description the description of this v cal
	 */
	public void setDescription(String description);

	/**
	 * Returns the guest of this v cal.
	 *
	 * @return the guest of this v cal
	 */
	@AutoEscape
	public String getGuest();

	/**
	 * Sets the guest of this v cal.
	 *
	 * @param guest the guest of this v cal
	 */
	public void setGuest(String guest);

	/**
	 * Returns the location of this v cal.
	 *
	 * @return the location of this v cal
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this v cal.
	 *
	 * @param location the location of this v cal
	 */
	public void setLocation(String location);

	/**
	 * Returns the time of this v cal.
	 *
	 * @return the time of this v cal
	 */
	@AutoEscape
	public String getTime();

	/**
	 * Sets the time of this v cal.
	 *
	 * @param time the time of this v cal
	 */
	public void setTime(String time);

	/**
	 * Returns the start date of this v cal.
	 *
	 * @return the start date of this v cal
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this v cal.
	 *
	 * @param startDate the start date of this v cal
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this v cal.
	 *
	 * @return the end date of this v cal
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this v cal.
	 *
	 * @param endDate the end date of this v cal
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the status of this v cal.
	 *
	 * @return the status of this v cal
	 */
	public long getStatus();

	/**
	 * Sets the status of this v cal.
	 *
	 * @param status the status of this v cal
	 */
	public void setStatus(long status);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VCal vCal);

	public int hashCode();

	public CacheModel<VCal> toCacheModel();

	public VCal toEscapedModel();

	public String toString();

	public String toXmlString();
}