/**
 * Copyright (c) Vietsoftware, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vlinksman.model.impl;

import com.vportal.portlet.vlinksman.model.LinkGroup;

/**
 * The extended model base implementation for the LinkGroup service. Represents a row in the &quot;LinkGroup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LinkGroupImpl}.
 * </p>
 *
 * @author LongLH
 * @see LinkGroupImpl
 * @see com.vportal.portlet.vlinksman.model.LinkGroup
 * @generated
 */
public abstract class LinkGroupBaseImpl extends LinkGroupModelImpl
	implements LinkGroup {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a link group model instance should use the {@link LinkGroup} interface instead.
	 */
}