/**
 * Copyright (c) Vietsoftware, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vsitemap.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.search.Indexer;
import com.liferay.portal.kernel.search.IndexerRegistryUtil;
import com.liferay.portal.kernel.search.SearchException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.vportal.portlet.vsitemap.model.VsmBranch;
import com.vportal.portlet.vsitemap.service.VsmBranchLocalService;
import com.vportal.portlet.vsitemap.service.VsmBranchService;
import com.vportal.portlet.vsitemap.service.persistence.VsmBranchPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the vsm branch local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.vportal.portlet.vsitemap.service.impl.VsmBranchLocalServiceImpl}.
 * </p>
 *
 * @author LongLH
 * @see com.vportal.portlet.vsitemap.service.impl.VsmBranchLocalServiceImpl
 * @see com.vportal.portlet.vsitemap.service.VsmBranchLocalServiceUtil
 * @generated
 */
public abstract class VsmBranchLocalServiceBaseImpl
	implements VsmBranchLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.vportal.portlet.vsitemap.service.VsmBranchLocalServiceUtil} to access the vsm branch local service.
	 */

	/**
	 * Adds the vsm branch to the database. Also notifies the appropriate model listeners.
	 *
	 * @param vsmBranch the vsm branch
	 * @return the vsm branch that was added
	 * @throws SystemException if a system exception occurred
	 */
	public VsmBranch addVsmBranch(VsmBranch vsmBranch)
		throws SystemException {
		vsmBranch.setNew(true);

		vsmBranch = vsmBranchPersistence.update(vsmBranch, false);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(vsmBranch);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return vsmBranch;
	}

	/**
	 * Creates a new vsm branch with the primary key. Does not add the vsm branch to the database.
	 *
	 * @param branchId the primary key for the new vsm branch
	 * @return the new vsm branch
	 */
	public VsmBranch createVsmBranch(long branchId) {
		return vsmBranchPersistence.create(branchId);
	}

	/**
	 * Deletes the vsm branch with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param branchId the primary key of the vsm branch
	 * @throws PortalException if a vsm branch with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteVsmBranch(long branchId)
		throws PortalException, SystemException {
		VsmBranch vsmBranch = vsmBranchPersistence.remove(branchId);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(vsmBranch);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Deletes the vsm branch from the database. Also notifies the appropriate model listeners.
	 *
	 * @param vsmBranch the vsm branch
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteVsmBranch(VsmBranch vsmBranch) throws SystemException {
		vsmBranchPersistence.remove(vsmBranch);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(vsmBranch);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return vsmBranchPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return vsmBranchPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return vsmBranchPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return vsmBranchPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public VsmBranch fetchVsmBranch(long branchId) throws SystemException {
		return vsmBranchPersistence.fetchByPrimaryKey(branchId);
	}

	/**
	 * Returns the vsm branch with the primary key.
	 *
	 * @param branchId the primary key of the vsm branch
	 * @return the vsm branch
	 * @throws PortalException if a vsm branch with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public VsmBranch getVsmBranch(long branchId)
		throws PortalException, SystemException {
		return vsmBranchPersistence.findByPrimaryKey(branchId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return vsmBranchPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the vsm branchs.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of vsm branchs
	 * @param end the upper bound of the range of vsm branchs (not inclusive)
	 * @return the range of vsm branchs
	 * @throws SystemException if a system exception occurred
	 */
	public List<VsmBranch> getVsmBranchs(int start, int end)
		throws SystemException {
		return vsmBranchPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of vsm branchs.
	 *
	 * @return the number of vsm branchs
	 * @throws SystemException if a system exception occurred
	 */
	public int getVsmBranchsCount() throws SystemException {
		return vsmBranchPersistence.countAll();
	}

	/**
	 * Updates the vsm branch in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param vsmBranch the vsm branch
	 * @return the vsm branch that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public VsmBranch updateVsmBranch(VsmBranch vsmBranch)
		throws SystemException {
		return updateVsmBranch(vsmBranch, true);
	}

	/**
	 * Updates the vsm branch in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param vsmBranch the vsm branch
	 * @param merge whether to merge the vsm branch with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the vsm branch that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public VsmBranch updateVsmBranch(VsmBranch vsmBranch, boolean merge)
		throws SystemException {
		vsmBranch.setNew(false);

		vsmBranch = vsmBranchPersistence.update(vsmBranch, merge);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(vsmBranch);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return vsmBranch;
	}

	/**
	 * Returns the vsm branch local service.
	 *
	 * @return the vsm branch local service
	 */
	public VsmBranchLocalService getVsmBranchLocalService() {
		return vsmBranchLocalService;
	}

	/**
	 * Sets the vsm branch local service.
	 *
	 * @param vsmBranchLocalService the vsm branch local service
	 */
	public void setVsmBranchLocalService(
		VsmBranchLocalService vsmBranchLocalService) {
		this.vsmBranchLocalService = vsmBranchLocalService;
	}

	/**
	 * Returns the vsm branch remote service.
	 *
	 * @return the vsm branch remote service
	 */
	public VsmBranchService getVsmBranchService() {
		return vsmBranchService;
	}

	/**
	 * Sets the vsm branch remote service.
	 *
	 * @param vsmBranchService the vsm branch remote service
	 */
	public void setVsmBranchService(VsmBranchService vsmBranchService) {
		this.vsmBranchService = vsmBranchService;
	}

	/**
	 * Returns the vsm branch persistence.
	 *
	 * @return the vsm branch persistence
	 */
	public VsmBranchPersistence getVsmBranchPersistence() {
		return vsmBranchPersistence;
	}

	/**
	 * Sets the vsm branch persistence.
	 *
	 * @param vsmBranchPersistence the vsm branch persistence
	 */
	public void setVsmBranchPersistence(
		VsmBranchPersistence vsmBranchPersistence) {
		this.vsmBranchPersistence = vsmBranchPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.vportal.portlet.vsitemap.model.VsmBranch",
			vsmBranchLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.vportal.portlet.vsitemap.model.VsmBranch");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	protected Class<?> getModelClass() {
		return VsmBranch.class;
	}

	protected String getModelClassName() {
		return VsmBranch.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = vsmBranchPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = VsmBranchLocalService.class)
	protected VsmBranchLocalService vsmBranchLocalService;
	@BeanReference(type = VsmBranchService.class)
	protected VsmBranchService vsmBranchService;
	@BeanReference(type = VsmBranchPersistence.class)
	protected VsmBranchPersistence vsmBranchPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private static Log _log = LogFactoryUtil.getLog(VsmBranchLocalServiceBaseImpl.class);
	private String _beanIdentifier;
}