/**
 * Copyright (c) Vietsoftware, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vcms.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import com.vportal.portlet.vcms.model.VcmsPARelation;
import com.vportal.portlet.vcms.model.VcmsPARelationModel;
import com.vportal.portlet.vcms.model.VcmsPARelationSoap;
import com.vportal.portlet.vcms.service.persistence.VcmsPARelationPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.List;

/**
 * The base model implementation for the VcmsPARelation service. Represents a row in the &quot;VcmsPARelation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.vportal.portlet.vcms.model.VcmsPARelationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VcmsPARelationImpl}.
 * </p>
 *
 * @author hai
 * @see VcmsPARelationImpl
 * @see com.vportal.portlet.vcms.model.VcmsPARelation
 * @see com.vportal.portlet.vcms.model.VcmsPARelationModel
 * @generated
 */
@JSON(strict = true)
public class VcmsPARelationModelImpl extends BaseModelImpl<VcmsPARelation>
	implements VcmsPARelationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vcms p a relation model instance should use the {@link com.vportal.portlet.vcms.model.VcmsPARelation} interface instead.
	 */
	public static final String TABLE_NAME = "VcmsPARelation";
	public static final Object[][] TABLE_COLUMNS = {
			{ "portionId", Types.VARCHAR },
			{ "articleId", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table VcmsPARelation (portionId VARCHAR(75) not null,articleId VARCHAR(75) not null,primary key (portionId, articleId))";
	public static final String TABLE_SQL_DROP = "drop table VcmsPARelation";
	public static final String ORDER_BY_JPQL = " ORDER BY vcmsPARelation.id.articleId DESC, vcmsPARelation.id.portionId DESC";
	public static final String ORDER_BY_SQL = " ORDER BY VcmsPARelation.articleId DESC, VcmsPARelation.portionId DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.vportal.portlet.vcms.model.VcmsPARelation"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.vportal.portlet.vcms.model.VcmsPARelation"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.vportal.portlet.vcms.model.VcmsPARelation"),
			true);
	public static long ARTICLEID_COLUMN_BITMASK = 1L;
	public static long PORTIONID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VcmsPARelation toModel(VcmsPARelationSoap soapModel) {
		VcmsPARelation model = new VcmsPARelationImpl();

		model.setPortionId(soapModel.getPortionId());
		model.setArticleId(soapModel.getArticleId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VcmsPARelation> toModels(VcmsPARelationSoap[] soapModels) {
		List<VcmsPARelation> models = new ArrayList<VcmsPARelation>(soapModels.length);

		for (VcmsPARelationSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.vportal.portlet.vcms.model.VcmsPARelation"));

	public VcmsPARelationModelImpl() {
	}

	public VcmsPARelationPK getPrimaryKey() {
		return new VcmsPARelationPK(_portionId, _articleId);
	}

	public void setPrimaryKey(VcmsPARelationPK primaryKey) {
		setPortionId(primaryKey.portionId);
		setArticleId(primaryKey.articleId);
	}

	public Serializable getPrimaryKeyObj() {
		return new VcmsPARelationPK(_portionId, _articleId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((VcmsPARelationPK)primaryKeyObj);
	}

	public Class<?> getModelClass() {
		return VcmsPARelation.class;
	}

	public String getModelClassName() {
		return VcmsPARelation.class.getName();
	}

	@JSON
	public String getPortionId() {
		if (_portionId == null) {
			return StringPool.BLANK;
		}
		else {
			return _portionId;
		}
	}

	public void setPortionId(String portionId) {
		_columnBitmask = -1L;

		if (_originalPortionId == null) {
			_originalPortionId = _portionId;
		}

		_portionId = portionId;
	}

	public String getOriginalPortionId() {
		return GetterUtil.getString(_originalPortionId);
	}

	@JSON
	public String getArticleId() {
		if (_articleId == null) {
			return StringPool.BLANK;
		}
		else {
			return _articleId;
		}
	}

	public void setArticleId(String articleId) {
		_columnBitmask = -1L;

		if (_originalArticleId == null) {
			_originalArticleId = _articleId;
		}

		_articleId = articleId;
	}

	public String getOriginalArticleId() {
		return GetterUtil.getString(_originalArticleId);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public VcmsPARelation toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (VcmsPARelation)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		VcmsPARelationImpl vcmsPARelationImpl = new VcmsPARelationImpl();

		vcmsPARelationImpl.setPortionId(getPortionId());
		vcmsPARelationImpl.setArticleId(getArticleId());

		vcmsPARelationImpl.resetOriginalValues();

		return vcmsPARelationImpl;
	}

	public int compareTo(VcmsPARelation vcmsPARelation) {
		int value = 0;

		value = getArticleId().compareTo(vcmsPARelation.getArticleId());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		value = getPortionId().compareTo(vcmsPARelation.getPortionId());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		VcmsPARelation vcmsPARelation = null;

		try {
			vcmsPARelation = (VcmsPARelation)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		VcmsPARelationPK primaryKey = vcmsPARelation.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		VcmsPARelationModelImpl vcmsPARelationModelImpl = this;

		vcmsPARelationModelImpl._originalPortionId = vcmsPARelationModelImpl._portionId;

		vcmsPARelationModelImpl._originalArticleId = vcmsPARelationModelImpl._articleId;

		vcmsPARelationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VcmsPARelation> toCacheModel() {
		VcmsPARelationCacheModel vcmsPARelationCacheModel = new VcmsPARelationCacheModel();

		vcmsPARelationCacheModel.portionId = getPortionId();

		String portionId = vcmsPARelationCacheModel.portionId;

		if ((portionId != null) && (portionId.length() == 0)) {
			vcmsPARelationCacheModel.portionId = null;
		}

		vcmsPARelationCacheModel.articleId = getArticleId();

		String articleId = vcmsPARelationCacheModel.articleId;

		if ((articleId != null) && (articleId.length() == 0)) {
			vcmsPARelationCacheModel.articleId = null;
		}

		return vcmsPARelationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{portionId=");
		sb.append(getPortionId());
		sb.append(", articleId=");
		sb.append(getArticleId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.vportal.portlet.vcms.model.VcmsPARelation");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>portionId</column-name><column-value><![CDATA[");
		sb.append(getPortionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>articleId</column-name><column-value><![CDATA[");
		sb.append(getArticleId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = VcmsPARelation.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			VcmsPARelation.class
		};
	private String _portionId;
	private String _originalPortionId;
	private String _articleId;
	private String _originalArticleId;
	private long _columnBitmask;
	private VcmsPARelation _escapedModelProxy;
}